package schiffeversenken.spielbrett;

public enum FeldStatus {
    UNBEKANNT, WASSER, SCHLACHTSCHIFF, KREUZER_I, KREUZER_II, ZERSTOERER_I,ZERSTOERER_II,ZERSTOERER_III, UBOOT_I, UBOOT_II,UBOOT_III,UBOOT_IV,SCHIFF, VERSENKT;



}
